module Puzzle 
  (module Puzzle.Char
  ,module Puzzle.Dict
  ,module Puzzle.Math
  ,module Puzzle.Morse
  ,module Puzzle.TVTropes
  ,module Puzzle.Web
  ,module Puzzle.Scrabble
  ,module Puzzle.List
  ) where

import Puzzle.List
import Puzzle.Char
import Puzzle.Dict
import Puzzle.Math
import Puzzle.Morse
import Puzzle.TVTropes
import Puzzle.Web
import Puzzle.Scrabble